apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-serv
  labels:
    app: {{ .Values.appname }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.appname }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.appname }}-serv-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.appname }}-cont-port
